// Generated by: GPT-4o
// Prompt: INT8 signed MAC unit, synthesizable SystemVerilog, always_ff

module mac (
    input  wire               clk,
    input  wire               rst,
    input  wire signed [7:0]  a,
    input  wire signed [7:0]  b,
    output reg  signed [31:0] out
);

    initial begin
        out = 32'sd0;
    end

    always @(posedge clk) begin
        if (rst) begin
            out <= 32'sd0;
        end else begin
            out <= out + (a * b);
        end
    end

endmodule
