// Generated by: Claude Sonnet 4.6
// Prompt: INT8 signed MAC unit, synthesizable SystemVerilog, always_ff

module mac (
    input  logic        clk,
    input  logic        rst,
    input  logic [7:0]  a,
    input  logic [7:0]  b,
    output logic [31:0] out
);

    always_ff @(posedge clk) begin
        if (rst) begin
            out <= 32'd0;
        end else begin
            out <= out + a * b;
        end
    end

endmodule
